# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmigrator < Formula
  desc "Migrate Terraform Configuration and State"
  homepage "https://github.com/tfmigrator/cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfmigrator/cli/releases/download/v0.2.2/tfmigrator_darwin_amd64.tar.gz"
      sha256 "2197e1a7e4d482b99c3c4e80d64060d7ba309236c277defa87dbaee103f077f1"

      def install
        bin.install "tfmigrator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfmigrator/cli/releases/download/v0.2.2/tfmigrator_darwin_arm64.tar.gz"
      sha256 "c0c29f259a66d8a5cf1c2ae00edce22daad9840af14c5c0fcc5e8bcb08242740"

      def install
        bin.install "tfmigrator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfmigrator/cli/releases/download/v0.2.2/tfmigrator_linux_arm64.tar.gz"
      sha256 "1f5776d14945478ef9e09721d9d8f7d84c3af6a040c7dff427c5d97d99c4c1ed"

      def install
        bin.install "tfmigrator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfmigrator/cli/releases/download/v0.2.2/tfmigrator_linux_amd64.tar.gz"
      sha256 "4a54afaa4d822f31f01b864b681a854f1cfeaad31df2ed5c2bf66d497aa32421"

      def install
        bin.install "tfmigrator"
      end
    end
  end

  test do
    system "#{bin}/tfmigrator --version"
  end
end
