# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmigrator < Formula
  desc "Migrate Terraform Configuration and State"
  homepage "https://github.com/tfmigrator/cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfmigrator/cli/releases/download/v0.2.1/tfmigrator_darwin_amd64.tar.gz"
      sha256 "a967d1cdf3bc6897baa4ec6bffd8479d8e73a4b2fe97b07637d1e7e36c60bbcb"

      def install
        bin.install "tfmigrator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tfmigrator/cli/releases/download/v0.2.1/tfmigrator_linux_amd64.tar.gz"
      sha256 "652f13430c2571e5d5ca065dc7f1bf93e551248c252bce9d1d3f8e4596a2db05"

      def install
        bin.install "tfmigrator"
      end
    end
  end

  test do
    system "#{bin}/tfmigrator --version"
  end
end
